export const TOGGLE_USER = 'TOGGLE_USER';
export const SAVE_LIVE_MODE = 'SAVE_LIVE_MODE';
export const SAVE_CURRENCY_STATE = 'SAVE_CURRENCY_STATE';
export const SAVE_CRYPTO_CURRENCIES = 'SAVE_CRYPTO_CURRENCIES';
